### ISSUE TITLE
getting started on Windows 10 is it supported ?  npm ERR! notsup Unsupported platform for automation-seed@0.1.0:

### ISSUE THREAD

**Issue by KipRM** [nanlabs/automation-seed#19] opened 2023-10-18 23:01 UTC
### Describe the issue

I am having issues getting yarn test to run.
I probably don't have all the dependencies ?
505 5 $ yarn test:local
yarn run v1.22.19
error automation-seed@0.1.0: The platform "win32" is incompatible with this module.
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
515 15 $ fnm --version
fnm 1.35.1

504 4 $ npm --version
10.2.0

505 5 $ node --version
v18.17.1

506 6 $ yarn --version
1.22.19

additional observations:
/c/repo/automation_seed_webdriverIO___main__ (main)
516 16 $ npm install
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for automation-seed@0.1.0: wanted {"os":"linux,darwin","cpu":"x64,arm64"} (current: {"os":"win32
","cpu":"x64"})
npm ERR! notsup Valid os:   linux,darwin
npm ERR! notsup Actual os:  win32
npm ERR! notsup Valid cpu:  x64,arm64
npm ERR! notsup Actual cpu: x64

npm ERR! A complete log of this run can be found in: C:\Users\kmartin\AppData\Local\npm-cache\_logs\2023-10-18T23_03_44_742Z-debug-0.
log

### Links

README.md ??

**Comment by jesinnott** [comment] 2023-10-27 21:55
Hey @KipRM thanks for create this issue. I've been unavailable these days and I was not able to reach out to you before. I pushed a fix in master updating the package.json for allow use windows platform. You can pull the latest changes and let me know if the issue is fixed

**Comment by KipRM** [comment] 2023-10-27 23:55
This looks much closer.  Now it's only indicating there isn't a spec to run. 

PS D:\repo\automation_seed_webdriverIO___main__> yarn
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.15s.
PS D:\repo\automation_seed_webdriverIO___main__> yarn test
yarn run v1.22.19
$ wdio run wdio.conf.js --no-autoCompileOpts.autoCompile
No capabilities selected!

Execution of 0 workers started at 2023-10-27T23:26:42.085Z

2023-10-27T23:26:42.133Z INFO @wdio/cli:launcher: Run onPrepare hook
// Test execution has started //
2023-10-27T23:26:44.967Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure
2023-10-27T23:26:44.967Z INFO @wdio/cli:launcher: Run onComplete hook
// Test execution has completed //
2023-10-27T23:26:44.970Z INFO @wdio/selenium-standalone-service: shutting down all browsers

Spec Files:      0 passed, 0 total (0% completed) in 00:00:02

2023-10-27T23:26:44.971Z INFO @wdio/local-runner: Shutting down spawned worker
2023-10-27T23:26:45.223Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-10-27T23:26:45.224Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jesinnott** [comment] 2023-10-28 00:01
You can take a look to the README, there are examples and steps to execute the tests. Basically you can run yarn test:{local or remote} and you can specify the --spec flag with the path. I'll close it since the original issue is solved

**Comment by jesinnott** [comment] 2023-10-28 00:02
closing it as Resolved

**Closed by jesinnott** 2023-10-28 00:02 UTC
Labels: documentation

**Comment by KipRM** [comment] 2023-10-29 01:31
Seems like this should be functioning but it appears My environment doesn't know my Capabilities setting ?  It shows an error when I include :local

PS D:\repo\automation_seed_webdriverIO___main__> ls ./test/specs/**/*.ts


    Directory: D:\repo\automation_seed_webdriverIO___main__\test\specs\added_subFolder


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        10/17/2023   9:06 PM            566 examplee2e.ts


PS D:\repo\automation_seed_webdriverIO___main__> yarn test --spec "./test/specs/**/*.ts"
yarn run v1.22.19
$ wdio run wdio.conf.js --no-autoCompileOpts.autoCompile --spec ./test/specs/**/*.ts
No capabilities selected!

Execution of 0 workers started at 2023-10-29T01:21:14.045Z

2023-10-29T01:21:14.098Z INFO @wdio/cli:launcher: Run onPrepare hook
// Test execution has started //
2023-10-29T01:21:16.551Z ERROR @wdio/cli:launcher: No specs found to run, exiting with failure
2023-10-29T01:21:16.551Z INFO @wdio/cli:launcher: Run onComplete hook
// Test execution has completed //
2023-10-29T01:21:16.552Z INFO @wdio/selenium-standalone-service: shutting down all browsers

Spec Files:      0 passed, 0 total (0% completed) in 00:00:02

2023-10-29T01:21:16.557Z INFO @wdio/local-runner: Shutting down spawned worker
2023-10-29T01:21:16.821Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
2023-10-29T01:21:16.822Z INFO @wdio/local-runner: shutting down
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\repo\automation_seed_webdriverIO___main__> yarn test:local --spec "./test/specs/**/*.ts"
yarn run v1.22.19
$ MODE=local yarn test --spec ./test/specs/**/*.ts
Invalid parameter - =local
error Command failed with exit code 4294967295.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\repo\automation_seed_webdriverIO___main__>

**Comment by KipRM** [comment] 2023-10-30 02:15
Using a project .npmrc file with chromedriver_filepath=/path/to/ChromeDriver.exe

Is that expected to override the current chrome driver in node modules ?
I have created a sh that appends it in path and added it to project .npmrc with no luck preventing it from picking up chromedriver version .114

**Comment by ulises-jeremias** [comment] 2023-10-30 03:55
@KipRM can you create another issue or GitHub discussion with the last comments you added? just to keep things more organized and then we can give you appropriate support 😊
